### ISSUE TITLE
Simplify lamassu-install and make it more platform-independent

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-scripts#20]
# Background

lamassu-install (https://github.com/lamassu/lamassu-scripts/blob/master/bin/lamassu-install) has served us well and has successfully set up dozens of droplets for our new operators. It's now becoming apparent, though, that Digital Ocean droplets aren't always the best choice. Specifically, they suck for running bitcoind because the disk space can't be easily resized and is extremely expensive compared to alternatives such as Amazon AWS and now Google Compute Engine. 

Since our operators now have to upgrade to 40GB droplets and will soon have to upgrade again, and because some of our operators just want to use their own servers, we want the install process to be less tailored to DO droplets. The install script should at least work with recent distributions of Ubuntu and Debian, and preferably with just about any Linux distro.
# Changes

Here's how I think I would do it now:
- How do we install PostgreSQL? Perhaps at this point we should require the user to install it first
- Perhaps we should use `trust` authentication for PostgreSQL, which would simplify things -- need to configure this in a cross-platform way
- Run as the current user, not root
- Use a node module like `forever` or `pm2`, not Upstart
- Use `crontab` to launch things on reboot, not Upstart
- Install npm packages locally, not globally (don't use `-g` option) but set up paths intelligently
- Retry on common network failures (not sure about this one)
- Make it idempotent: it should always be safe to run it again
- https://github.com/lamassu/lamassu-scripts/blob/master/bin/lamassu-bitcoind-install will also have to be made more platform independent

**Comment by naconner** [comment]
Less relevant with v3 and DigitalOcean's block volume storage.
