### ISSUE TITLE
Request: Script to insert bill count and fingerprint into dispenses

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-scripts#30]
Useful would be a script to take these user-supplied variables:

- Cartirdge 1 bill count
- Cartridge 2 bill count
- Fingerprint of Santo Tirso host device

And insert them into the `dispenses` postgres table.

As otherwise done manually with this command while in the lamassu database:

```
INSERT INTO dispenses (device_fingerprint, dispense1, reject1, count1, dispense2, reject2, count2, refill)
VALUES ('76:B6:3B:AE:F7:1B:9E:CF:7A:6E:31:61:9D:A7:D5:C7:25:5C:1A:1F', 0, 0, 40, 0, 0, 31, true);
```

**Comment by naconner** [comment]
Example using 100 notes in Cartridge 1 (upper), and 200 notes in Cartridge 2 (lower):

```
lamassu-billcount 93:39:CC:60:74:19:91:DD:D2:7E:44:9E:6A:94:7D:2E:E6:12:4A:18 100 200
```

A good feature would be if running `lamassu-billcount` without arguments, it would show currently paired devices with their respective bill counts:

```
root@santo-tirso:~# lamassu-billcount

Currently paired devices and bill counts:
name: burrito-machine, fingerprint: 93:39:CC:60:74:19:91:DD:D2:7E:44:9E:6A:94:7D:2E:E6:12:4A:18, cartridge 1: 167, cartridge 2: 269
name: taco-truck, fingerprint: 92:9C:A2:60:AB:EE:E2:A5:84:DB:FB:FC:C8:DC:C7:C3:24:A9:87:F0
```

**Comment by joshmh** [comment]
Yeah, we should use name instead of fingerprint for this, and make sure name is set to something.

**Comment by naconner** [comment]
Is there an easy way for an operator to set the name apart from going into psql?

**Comment by joshmh** [comment]
https://github.com/lamassu/lamassu-scripts/commit/a433420bb14191de056e7d8878bf8169d7d3bfdb

and

https://github.com/lamassu/lamassu-scripts/commit/744fb62c147f8af3c33dfe6ab9427b98da3d271c

**Comment by naconner** [comment]
Awesome. :+1: 

Although I see `pg` was removed from the dependencies, yet `ssu-name`  requires it: https://gist.github.com/naconner/b8b4d9c83e6fdaee488a
