### ISSUE TITLE
Request: Script to create cartridges.json file with denominations

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-scripts#31]
Usefull would be a script to take two user-supplied variables:

- Cartridge 1 denomination
- Cartridge 2 denomination

And creates/inserts them into the file `catridges.json` within the lamassu-server directory.

Sample:

```
{
  "cartridges": [5, 20],
  "virtualCartridges": [5]
}
```

**Comment by joshmh** [comment]
https://github.com/lamassu/lamassu-scripts/commit/7bea96dafc8061a497aa01a720111a335367638d
