### ISSUE TITLE
Should we merge scripts into lamassu-server?

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-scripts#38]
Merging active scripts into lamassu-server should simplify installation and upgrade. Any reason not to do this? @naconner

**Comment by naconner** [comment]
The update cycle of lamassu-server is shorter than that of lamassu-scripts, so it's not an issue to me.

However, if these same scripts are included in the next lamassu-server release, then npm installation will break when it finds they already exist in /usr/local/bin/.

**Comment by naconner** [comment]
No longer relevant with v3.
