### ISSUE TITLE
invalid API use

### ISSUE THREAD

**Issue by vitaly-t** [lamassu/lamassu-scripts#42]
https://github.com/lamassu/lamassu-scripts/blob/db7eb3869bf96fd5a7acecc66314bd9ce4e29846/bin/ssu-cartridges#L71

this condition will never happen, see `many` API: http://vitaly-t.github.io/pg-promise/Database.html#.many

**Comment by joshmh** [comment]
Thanks, @vitaly-t. We just moved over to pg-promise from a different library where we had to check for those things. Good catch.

Btw, how did you find this repo?

**Comment by vitaly-t** [comment]
GitHub search engine shows all new entries against the library.

What was the library, by the way? :)

**Comment by joshmh** [comment]
It was https://github.com/sapienlab/dbh-pg.

And thanks for pg-promise -- great library!

**Comment by vitaly-t** [comment]
Alright, that's an oldie :)

Cheers!

**Comment by joshmh** [comment]
Fixed in https://github.com/lamassu/lamassu-scripts/commit/4e62b071fe18835fe9aa684a86bfc2904dc9fec7

**Comment by vitaly-t** [comment]
Just so, `manyOrNone` has a shorter alias - `any` ;)

**Comment by joshmh** [comment]
Thanks, that will come in handy. I must have missed that!

Josh Harvey
Co-founder
*Lamassu, Inc.*
https://lamassu.is
