### ISSUE TITLE
DB: transactions table -> ID used to be UUID not integer, change back?

### ISSUE THREAD

**Issue by richardsj** [lamassu/lamassu-scripts#46]
UUID has a variety of advantages over integer as a primary key.  Amongst the many is the fact that when transactions from a variety of servers get merged, they don't conflict with each other, since their uniqueness is all-but-guaranteed.

In 1.x it used to be UUID, was there a reason not to continue that tradition, so that future DB extracts can be merged/split at will?  People tend to run a server per machine at the moment for fine-grained control but merging reporting later is easier with UUIDs as primary keys for records. @joshmh

**Comment by joshmh** [comment]
Good points @richardsj. See https://github.com/lamassu/lamassu-scripts/issues/47 for info about the latest db schema. The main tx tables are now UUID, but many other tables are still serial. I'll go and change all those to UUID.

**Comment by joshmh** [comment]
Moved to: https://github.com/lamassu/lamassu-server/issues/63
